### PR TITLE
Add CLK tree

### PR DESCRIPTION
**Pull request by MiloCasagrande**
Signed-off-by: Milo Casagrande <milo@opensourcefoundries.com>

### CODE REVIEW

**Comment by gctucker** [comment]
@MiloCasagrande no email reports for this tree?

**Comment by MiloCasagrande** [comment]
I thought they all went automatically to the public mailing list. Will update.

**Comment by gctucker** [comment]
Thanks.  Also please rebase as I've merged Tomeu's PR which added his tree (should be trivial).

**Comment by MiloCasagrande** [comment]
OK, now it's ready.

**Comment by gctucker** [comment]
Thanks.  Which branches do you want to add from that tree?  Also, are we OK with the extra load on builders and should we enable it to run in all the labs?
@khilman @mattface

**Comment by khilman** [comment]
In their original request (by email), the maintainers asked for only the clk-next branch.  
This is a pretty low change-rate tree/branch, so IMO, enabling it for all the labs seems OK, but @matface should probably make the final call based on current build throughput.

**Comment by mturquette** [comment]
Hi all,

Moving the discussion away from email over to this PR.

Stephen and I both requested to use some dedicated aliases to reduce mailing list spam:

sboyd+clkci@kernel.org
mturquette+clkci@baylibre.com

I never saw any mail to those address nor to the mailing list, and I cannot find the clk tree when searching on kernelci.org.

Is there something else needed to enable testing of the clk tree? Did I just somehow miss it?

Thanks!
Mike

**Comment by khilman** [comment]
Looks like the tree was added, but the jenkins job that decides which branches within the trees to check was not updated.  Unfortunately, that's still a manual process until we can move to Jenkins pipeline jobs.

Anyways, I've added it manually now, so keep an eye on kernelci.org/job/clk/ and let us know if you don't see any emails after jobs start showing up there.

**Comment by mturquette** [comment]
Thanks! I'll keep an eye on it.

**Pull request merged**
