### PR TITLE
Add a Jenkins job to build Debian images

### PR DESCRIPTION
**Pull request by tomeuv**
The images are suitable for NFS roots, and the corresponding ramdisks
are extracted and uploaded.

Currently images for arm64, armhf, x86 and x86_64 are generated.

The hostname is set to "debian" and the root user can login without
password.

The images don't contain a kernel, modules nor firmware.

### CODE REVIEW

**Comment by tomeuv** [comment]
You will see that currently depends on credentials available only on collabora's jenkins, and uploads to collabora's servers. Please advise on how this should be done instead. Thanks!

**Comment by khilman** [comment]
From: https://ci.kernelci.org/job/buildroot-builder/configure (not sure if you have perms here, bug Guillaume does).  Note that API_TOKEN is a jenkins "Secret Text" variable.

This is how images are pushed for the buildroot roofs images.`
(rm -rf kernelci-build; git clone --depth 1 https://github.com/kernelci/kernelci-build-staging.git kernelci-build)
export PATH=$PATH:$PWD/kernelci-build
PUBLISH_PATH=images/rootfs/buildroot/$(git describe)/${arch}/${frag}

(cd output/images; push-source.py --token ${API_TOKEN} --api ${API} --publish_path ${PUBLISH_PATH} --file *)

`

**Comment by khilman** [comment]
Minor, but can you also create a `rootfs.cpio.gz` symlink to the initramfs.img.  I think some of the LAVA tooling depends on the .gz suffix to know how to unpack/repack the ramdisk.

**Comment by tomeuv** [comment]
> Minor, but can you also create a rootfs.cpio.gz symlink to the initramfs.img. I think some of the LAVA tooling depends on the .gz suffix to know how to unpack/repack the ramdisk.

Couldn't find a way to upload symlinks with push_source.py, but the ramdisk file already ends up in .gz, so I guess there shouldn't be any problem?

**Comment by khilman** [comment]
OK, if the ramdisk already ends in .gz, that's all that's needed.

**Comment by tomeuv** [comment]
@ana is refactoring these scripts to make it easier to add more jobs for more test suites.

**Pull request closed without merging**
